<font face="微软雅黑">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 第三章：关联方法与关联矩阵

---

本章内容简介：

- 3.1 Objectives
- 3.2 The Main Categories of Association Measures (Short Overview)
- 3.3 Q Mode: Computing Dissimilarity Matrices Among Objects
- 3.4 R Mode: Computing Dependence Matrices Among Variables
- 3.5 Pre-transformations for Species Data
- 3.6 Conclusion

## 3.1 Objectives

## 3.2 The Main Categories of Association Measures (Short Overview)

### 3.2.1 Q Mode and R Mode

### 3.2.2 Symmetrical or Asymmetrical Coefficients in Q Mode: The Double-Zero Problem

### 3.2.3 Association Measures for Qualitative or Quantitative Data

### 3.2.4 To Summarize...

## 3.3 Q Mode: Computing Dissimilarity Matrices Among Objects

### 3.3.1 Q Mode: Quantitative Species Data

### 3.3.2 Q Mode: Binary (Presence-Absence) Species Data

### 3.3.3 Q Mode: Quantitative Data (Excluding Species Abundances)

### 3.3.4 Q Mode: Binary Data (Excluding Species Presence-Absence Data)

### 3.3.5 Q Mode: Mixed Types Including Categorical(Qualitative Multiclass) Variables

## 3.4 R Mode: Computing Dependence Matrices Among Variables

### 3.4.1 R Mode: Species Abundance Data

### 3.4.2 R Mode: Species Presence-Absence Data

### 3.4.3 R Mode: Quantitative and Ordinal Data (Other than Species Abundances)

### 3.4.4 R Mode: Binary Data (Other than Species Abundance Data)

## 3.5 Pre-transformations for Species Data

## 3.6 Conclusion


</font>