<font face="微软雅黑">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 第七章：生态数据的空间分析

本章内容简介：

- 7.1 Objectives
- 7.2 Spatial Structures and Spatial Analysis: A Short Overview
- 7.3 Multivariate Trend-Surface Analysis
- 7.4 Eigenvector-Based Spatial Variables and Spatial Modelling
- 7.5 Another Way to Look at Spatial Structures: Multiscale Ordination (MSO)
- 7.6 Space-Time Interaction Test in Multivariate ANOVA, Without Replicates
- 7.7 Conclusion

## 7.1 Objectives

## 7.2 Spatial Structures and Spatial Analysis: A Short Overview

### 7.2.1 Introduction

### 7.2.2 Induced Spatial Dependence and Spatial Autocorrelation

### 7.2.3 Spatial Scale

### 7.2.4 Spatial Heterogeneity

### 7.2.5 Spatial Correlation or Autocorrelation Functions and Spatial Correlograms

### 7.2.6 Testing for the Presence of Spatial Correlation: Conditions

### 7.2.7 Modelling Spatial Structures

## 7.3 Multivariate Trend-Surface Analysis

### 7.3.1 Introduction

### 7.3.2 Trend-Surface Analysis in Practice

## 7.4 Eigenvector-Based Spatial Variables and Spatial Modelling

### 7.4.1 Introduction

### 7.4.2 Distance-Based Morans Eigenvector Maps (dbMEM) and Principal Coordinates of Neighbour Matrices (PCNM)

### 7.4.3 MEM in a Wider Context: Weights Other than Geographic Distances

### 7.4.4 MEM with Positive or Negative Spatial Correlation: Which Ones should Be Used?

### 7.4.5 Asymmetric Eigenvector Maps (AEM): When Directionality Matters

#### 7.4.5.1 Introduction

#### 7.4.5.2 Principle and Application of the Method

## 7.5 Another Way to Look at Spatial Structures: Multiscale Ordination (MSO)

### 7.5.1 Principle

### 7.5.2 Application to the Mite Data ? Exploratory Approach

### 7.5.3 Application to the Detrended Mite and Environmental Data

## 7.6 Space-Time Interaction Test in Multivariate ANOVA, Without Replicates

### 7.6.1 Introduction

### 7.6.2 Testing the Space-Time Interaction with the sti Functions

## 7.7 Conclusion


</font>